In [1]:
import numpy as np

# Bir listeyi NumPy listesine dönüştürme 

# 1D array creation functions

### np.arange(n) = 0 - n arası sayılardan oluşan dizi oluşturur.

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.arange(x,y,n) = x - y aralığında ve artım miktarı n kadar olan bir dizi oluşturur.

In [3]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

### numpy.linspace(x,y,n) = x - y aralığında ve n adet eşit aralıklı kesirli sayılardan oluşan bir dizi oluşturur.

In [4]:
np.linspace(1., 4., 5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

### np.random.randint(x,y,n) = x - y aralığında rastgele tam sayılardan oluşan n elemanlı bir dizi oluşturur.

In [5]:
np.random.randint(1,100,10)

array([25,  5,  5, 84, 84, 30, 28, 59, 89,  5])

### np.random.random(n) = 0 - 1 arasında rastgele kesirli sayılardan oluşan n elemanlı bir dizi oluşturur.

In [6]:
np.random.random(5)

array([0.8626179 , 0.575262  , 0.41468435, 0.2594566 , 0.68622507])

# 2D array creation functions

### np.array([],[]) = İç içe listeleri NumPy matrisine dönüştürür.

In [7]:
np.array([[2,3,4],[5,6,7]])

array([[2, 3, 4],
       [5, 6, 7]])

### np.eye(n,dtype = int) = n elemanlı birim matris oluşturur. dtype= kullanımı zorunlu değildir.

In [8]:
np.eye(7, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [9]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

### np.eye(x, y) = x satır y sütun kadar birim matris oluşturur.

In [10]:
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

### np.zeros((x,y),dtype = int) = x satır y sütun 0'dan oluşan bir dizi oluşturur

In [11]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### np.ones((x,y),dtype = int) = x satır y sütun 1'den oluşan bir dizi oluşturur

In [12]:
np.ones((3,6),dtype = int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

### np.random.randint(x,y, [n,m]) = x - y aralığında rastgele tam sayılardan oluşan n satır m sütunlu matris oluşturur.

In [13]:
np.random.randint(1,100,[3,6])

array([[87, 41, 60, 84, 32,  1],
       [67, 75, 68, 59, 46, 90],
       [13,  4, 97, 16, 51, 71]])

### np.random.random((x , y)) = 0 - 1 aralığında x satır , y sütunlu kesirli sayılardan oluşan bir matris oluşturur.

In [14]:
np.random.random((3,6))

array([[0.90401884, 0.32757603, 0.69520135, 0.33346594, 0.28244199,
        0.92951071],
       [0.06632356, 0.61043464, 0.65989917, 0.88743317, 0.9123103 ,
        0.34391723],
       [0.38511563, 0.91450599, 0.57938681, 0.95810903, 0.94948396,
        0.20996318]])

### np.random.randn(x , y) = x satır y sütunlu rastgele kesirli sayılardan oluşan bir matris oluşturur. 

In [15]:
np.random.randn(3 , 6)

array([[ 0.20674051, -0.02773385, -0.80644011, -0.11060281,  0.02945042,
        -0.05298546],
       [ 1.9573186 , -0.7554828 , -1.68029842,  1.09291235,  2.07797093,
         0.26403844],
       [ 0.78450979, -1.56157993,  0.51416066, -0.40427122, -0.71252356,
        -0.49239529]])

# NumPy Veri Tipi

In [16]:
a = np.arange(5)

### Dizinin type bilgisini döndürme

In [17]:
a.dtype

dtype('int32')

### Dizinin boyutsal şeklini döndürme

In [18]:
a.shape

(5,)

### Dizinin eleman sayısını gösterme

In [19]:
a.size

5

# 3 BOYUTLU BİR DİZİ TANIMLAYIP ÖNCE 2 BOYUTA DAHA SONRA 1 BOYUTA DÖNDÜREN PROGRAM

In [20]:
boyut_3 = np.array([
    [[0,1,2],[3,4,5],[6,7,8]],
    [[9,10,11],[12,13,14],[15,16,17]],
    [[18,19,20],[21,22,23],[24,25,26]]
])
print("Dizinin boyutu: {0}" .format(boyut_3.ndim))
print("Dizinin boyutsal şekli: {0}" .format(boyut_3.shape))

Dizinin boyutu: 3
Dizinin boyutsal şekli: (3, 3, 3)


In [21]:
boyut_2 = boyut_3.reshape((3,9))
print(boyut_2)
print("Dizinin boyutu: {0}" .format(boyut_2.ndim))
print("Dizinin boyutsal şekli: {0}" .format(boyut_2.shape))

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]
Dizinin boyutu: 2
Dizinin boyutsal şekli: (3, 9)


In [22]:
boyut_1 = boyut_2.reshape(27)
print(boyut_1)
print("Dizinin boyutu: {0}" .format(boyut_1.ndim))
print("Dizinin boyutsal şekli: {0}" .format(boyut_1.shape))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
Dizinin boyutu: 1
Dizinin boyutsal şekli: (27,)


# Array Birleştirme

In [23]:
x = np.random.randint(1,100,10)
y = np.random.randint(1,100,10)
print(x,y)

[55 39 30 31 14 87 23  7 60 35] [28 64 46 72 70 57 27 17  9  2]


In [24]:
z = np.concatenate([x,y])
print(z)

[55 39 30 31 14 87 23  7 60 35 28 64 46 72 70 57 27 17  9  2]


In [25]:
z = np.concatenate([x,y])
print(z)

[55 39 30 31 14 87 23  7 60 35 28 64 46 72 70 57 27 17  9  2]


In [26]:
x = np.random.randint(1,100,[3,6])
y = np.random.randint(1,100,[3,6])
z = np.concatenate([x,y])
print("{0}\n{1}\n{2}".format(x,y,z))

[[80 54 35 35 85  5]
 [55 97 35 29 25 21]
 [98 44 52 30 21 58]]
[[35 14 63 18 56 18]
 [10 92 40  8 96 84]
 [68 90 29 68 23 30]]
[[80 54 35 35 85  5]
 [55 97 35 29 25 21]
 [98 44 52 30 21 58]
 [35 14 63 18 56 18]
 [10 92 40  8 96 84]
 [68 90 29 68 23 30]]


In [27]:
x = np.random.randint(1,100,[3,6])
y = np.random.randint(1,100,[3,6])
z = np.concatenate([x,y], axis=1)
print("{0}\n{1}\n{2}".format(x,y,z))

[[26  6 20 46 90 29]
 [36 53 45 79 89 40]
 [71 54 90 70 50 72]]
[[73 13 82 56 83 61]
 [87 37 24 86 49 61]
 [72 58 16 13 11 78]]
[[26  6 20 46 90 29 73 13 82 56 83 61]
 [36 53 45 79 89 40 87 37 24 86 49 61]
 [71 54 90 70 50 72 72 58 16 13 11 78]]


# Array Ayırma

In [28]:
x = np.random.randint(1,100,10)
a, b = np.split(x,[3])
c,d,e = np.split(x,[3,8])
print("{0}\n{1}\t{2}\n{3}\t{4}\t{5}".format(x,a,b,c,d,e))

[81 65 81 65 82 42 83 25 81 50]
[81 65 81]	[65 82 42 83 25 81 50]
[81 65 81]	[65 82 42 83 25]	[81 50]


In [29]:
x = np.random.randint(1,100,[6,6])
üst, alt = np.vsplit(x, [3])
print("{0}\n{1}\n{2}".format(x,üst,alt))

[[60 35 35 97 25 10]
 [30 91 40 48 45 16]
 [35 18 93 74 28 60]
 [35 45 47 61 54 97]
 [95 40 22 11 25 38]
 [76 23  3 94  1 13]]
[[60 35 35 97 25 10]
 [30 91 40 48 45 16]
 [35 18 93 74 28 60]]
[[35 45 47 61 54 97]
 [95 40 22 11 25 38]
 [76 23  3 94  1 13]]


In [30]:
x = np.random.randint(1,100,[8,8])
üst, orta, alt = np.vsplit(x, [3,5])

In [31]:
üst

array([[16, 99, 78, 55, 15, 59, 60, 29],
       [76,  9,  3, 78, 11,  4, 92, 85],
       [87, 23, 75, 79, 41, 16, 47, 92]])

In [32]:
orta

array([[36, 39,  3, 92, 61, 45, 28, 52],
       [65, 64, 43, 78, 72, 45, 93, 73]])

In [33]:
alt

array([[67, 33, 36, 25, 81, 89, 67, 93],
       [75, 90, 35, 71, 47,  7, 97, 92],
       [92,  5, 61, 80, 68, 47, 32, 21]])

# Arraylerde Sıralama

In [34]:
x = np.random.randint(1,100,10)
print("{0}\t{1}".format(x,np.sort(x)))

[94 61 18 33  1 30 43 20  5 55]	[ 1  5 18 20 30 33 43 55 61 94]


In [35]:
x = np.random.randint(1,100,[3,3])
print("{0}\n{1}\n{2}".format(x,np.sort(x,axis=1),np.sort(x,axis=0)))

[[45 95 15]
 [89 11 20]
 [32 87 28]]
[[15 45 95]
 [11 20 89]
 [28 32 87]]
[[32 11 15]
 [45 87 20]
 [89 95 28]]


In [36]:
import pandas as pd

# NumPy Dizisini Pandas DataFrame Dönüştürme = df = pd.DataFrame(diziAdı, columns=[sütunİsimleri],index=[indisNumaraları])

In [37]:
myArray = np.array([["ALİ",1996,2016],["CENGİZ",1974,1997],["ÖMER",2002,2020]])
df = pd.DataFrame(myArray, columns = ["Ad" , "Doğum Tarihi" , "İşe Başlama Tarihi"])
df

Ad Doğum Tarihi İşe Başlama Tarihi
0     ALİ         1996               2016
1  CENGİZ         1974               1997
2    ÖMER         2002               2020